-- MySQL Script generated by MySQL Workbench
-- mar. 07 déc. 2021 11:18:48
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema groupamania
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema groupamania
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `groupamania` ;
USE `groupamania` ;

-- -----------------------------------------------------
-- Table `groupamania`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `groupamania`.`users` (
  `user_id` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(20) NOT NULL,
  `lastname` VARCHAR(20) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(500) NOT NULL,
  `avatar` VARCHAR(45) NULL,
  `admin` TINYINT NOT NULL DEFAULT 0,
  PRIMARY KEY (`user_id`),
  UNIQUE INDEX `EMAIL_UNIQUE` (`email` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `groupamania`.`POSTS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `groupamania`.`POSTS` (
  `post_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `image` VARCHAR(45) NULL,
  `text` TEXT(500) NOT NULL,
  `post_like` INT NOT NULL DEFAULT 0,
  `post_dislike` INT NOT NULL DEFAULT 0,
  `post_love` INT NOT NULL DEFAULT 0,
  `post-celebrate` INT NOT NULL DEFAULT 0,
  `post_support` INT NOT NULL DEFAULT 0,
  `post_insighful` INT NOT NULL DEFAULT 0,
  `post_curious` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`post_id`, `user_id`),
  INDEX `fk_POSTS_USERS_idx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `post_users_fk1`
    FOREIGN KEY (`user_id`)
    REFERENCES `groupamania`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `groupamania`.`comments`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `groupamania`.`comments` (
  `comment_id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `post_id` INT NOT NULL,
  `text` TEXT(500) NOT NULL,
  `comment_like` INT NOT NULL DEFAULT 0,
  `comment-dislike` INT NOT NULL DEFAULT 0,
  `comment_love` INT NOT NULL DEFAULT 0,
  `comment_celebrate` INT NOT NULL DEFAULT 0,
  `comment_support` INT NOT NULL DEFAULT 0,
  `comment_insgihful` INT NOT NULL DEFAULT 0,
  `comment_curious` INT NOT NULL DEFAULT 0,
  PRIMARY KEY (`comment_id`, `user_id`, `post_id`),
  INDEX `fk_COMMENTS_USERS1_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_COMMENTS_POSTS1_idx` (`post_id` ASC) VISIBLE,
  CONSTRAINT `comments_users_fk1`
    FOREIGN KEY (`user_id`)
    REFERENCES `groupamania`.`users` (`user_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `comments_posts_fk1`
    FOREIGN KEY (`post_id`)
    REFERENCES `groupamania`.`POSTS` (`post_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
